### ISSUE TITLE
->archive_files returns list of fields

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-perl#19]
Writing tests I found that `$bdefile->archive_files` returns all field names, same as `$bdefile->fields`.
I think this is a real bug.

Documentation states:
```
    $bdefile->archive_files(files)
        Retrieve or specify the archive files to include with the data set. If the file is opened
        from a BdeRepository/BdeDataset then this will be automatically populated.
```

In this case the file was *not* opened from a BdeRepository/BdeDataset.

@palmerj should it return 'undef' instead ?

**Comment by strk** [comment]
Or, an empty array ?

**Comment by strk** [comment]
This is now skipped as a test here:
https://github.com/linz/linz_bde_perl/blob/master/t/BdeFile.t#L66-L69

Once decided, the archives support should also be put under proper testing

**Comment by strk** [comment]
@palmerj your opinion on this ? I'm thinking we could release 1.1.0 with the addition of the `::pipe` method (#23) and this is the only open ticket :)

**Comment by palmerj** [comment]
This feature isn't very much used anymore. But comes from days gone by when older BDE dataset directories were placed into the `path/level_x_archive` path. It's a bug and the lines that states the "fields" method should be "files". Just a typo.

**Comment by strk** [comment]
Thanks @palmerj - if you want to give your blessing to the typo fix: https://github.com/linz/linz-bde-perl/pull/34

**Comment by palmerj** [comment]
Still WIP
