### ISSUE TITLE
Allow streaming copy output via filedescriptor

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-perl#23]
Applications like linz_bde_uploader might want to avoid writing to a temporary file before feeding the BDE data to yet another destination (ie: PostgreSQL database). This class has a `copy` subroutine that takes a temporary file but I could not find one to open a streaming interface for that data. The underlying `bde_copy` should be already capable of doing that (at least on a unix system): see https://github.com/linz/linz_bde_copy/issues/31

**Comment by strk** [comment]
I'm not sure how a streaming Perl interface would look like, maybe a method returning a filehandle, like a "pipe" method to go with the "copy" one ?

**Comment by strk** [comment]
\cc @palmerj

**Comment by palmerj** [comment]
I think the interface would simply return a filehandle reference which the user then needs to manage. Back I haven't thought about that too much!

**Comment by strk** [comment]
Is it acceptable to have such `pipe` function bail out if `/dev/stdout` is not supported ?

**Comment by strk** [comment]
or, FIFO files (would be another way to do it)

**Comment by strk** [comment]
with FIFO files we actually dont' even need any support in this library but can be done directly by caller!

**Comment by strk** [comment]
See how you like #24 - no fifos used, only `/dev/stdout`

**Comment by imincik** [comment]
@strk , I can't comment on advantages of FIFO over `stdout` . I have no experience.

**Comment by palmerj** [comment]
Personally I would go with stdout as it's a more standard approach

**Comment by imincik** [comment]
@palmerj , thanks for your comment.

**Comment by strk** [comment]
It looks like it is not only windows lacking `/dev/stdout`:
https://github.com/linz/bde-processor-deployment/issues/66

**Comment by strk** [comment]
Closing again, moving the ::pipe problem to #26
