### ISSUE TITLE
Document Timezone of dataset timestamps

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-perl#31]
In https://github.com/linz/linz-bde-perl/blob/master/docs/BDE_repository.md it is documented that BDE datasets are named after  a timestamp (`YYYYMMDDhhmmss`) but it isn't specified WHICH timezone the time refers to. We should fix that.

NOTE: upload of historical dataset process is also affected by this

\cc @palmerj @billgeo @ccrook

**Comment by palmerj** [comment]
Looking at [this](https://github.com/linz/bde-download-scripts-private/blob/master/Scripts/get_bde_files.pl#L473) it seems to be the oldest file modified timestamp in the level_xxx unload directory on the crsprd1 server. crsprd1 time is NZDT:

```bash
bash-3.2$ date +%Z
NZDT
```

**Comment by palmerj** [comment]
> Looking at this it seems to be the oldest file modified timestamp in the level_xxx unload directory on the crsprd1 server. 

Confirmed this by looking at crsprd file timestamps and created directories on lds_data_staging.

Note `ss` part of the directory format is always `00`

**Comment by strk** [comment]
Depending on daylight saving the timezone in New Zealand
can be NZDT or NZST, is that what we're getting ?

It may be a good idea to convert all those timestamps
to UTC for them to be easier to be compared and avoid
time warps at DST kicking time ...

Anyway, it's good to document the _current_ timestamp
in that document file

**Comment by palmerj** [comment]
> It may be a good idea to convert all those timestamps
to UTC for them to be easier to be compared and avoid
time warps at DST kicking time ...

Yip and this could considered in the updates to the cde processing on crsprd1
