### ISSUE TITLE
Travis build fails: Failed to upconvert metadata to 1.1

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-perl#32]
From https://travis-ci.org/linz/linz-bde-perl/jobs/327652572#L527

> Failed to upconvert metadata to 1.1. Errors:
> Missing mandatory field, 'version' (version) [Validation: 1.0]

May be related to Travis updating the default distribution inuse

**Comment by imincik** [comment]
Tests are failing again. See: https://travis-ci.org/linz/linz-bde-perl/jobs/583088289

**Comment by strk** [comment]
Odd, build history has successes for the 1.2.0 tag as well:
https://travis-ci.org/linz/linz-bde-perl/builds

**Comment by strk** [comment]
Pull #53 seems to fix this again but it's weird that master build succeeded too, given they are exactly the same.
This seems to be an external issue (like a broken cpan module or something on Travis, occasionally showing up ?)

**Comment by strk** [comment]
Closed via #54
