### ISSUE TITLE
Package release 1.1.0

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-perl#42]
Once ready (#41)

**Comment by strk** [comment]
Tag is ready: https://github.com/linz/linz-bde-perl/releases/tag/1.1.0

**Comment by strk** [comment]
Do I still have to wait for packaging before targetting 1.1.1dev in branch ?
Meanwhile master can be targetted at 1.2.0: https://github.com/linz/linz-bde-perl/pull/44 (your approval welcome @imincik)

**Comment by imincik** [comment]
> Do I still have to wait for packaging before targetting 1.1.1dev in branch ?

Yes, I still don't have any workaround.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
Still useful to speedup uploads, this new release adds the pipe method

**Comment by imincik** [comment]
Will package today or tomorrow.

**Comment by imincik** [comment]
Package created and uploaded to `test`
