### ISSUE TITLE
Publish Bionic package

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-perl#47]
Once tested to be working via #46

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
Pushed to test repo:

Pushing build-area/liblinz-bde-perl_1.1.1-1linz~bionic1_all.deb... success!

Keeping open until promoted to production

**Comment by imincik** [comment]
@strk , we are promoting packages from `test` repo branch to `prod` after BDE Processor UAT is done (https://github.com/linz/bde-processor-deployment/wiki/Production-Deployment#production-deployment). I think we don't need this ticket. Will close it.
