### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by l0b0** [linz/linz-bde-perl#70]
Should be easier to maintain, and compatible with our other projects.
This is one of the last repositories LINZ has on Travis CI. So would be good to do this so we can cancel our Travis CI subscription.

- [x] Check that nothing depends on its result
- [x] Check whether anything in it should be moved into the GitHub actions
- [x] Delete the Travis CI configuration and anything related to it
- [x] Once it merges, tell @billgeo so he can cancel the Travis CI subscription.

**Comment by billgeo** [comment]
Already cancelled Travis.

**Comment by billgeo** [comment]
Looks like Github actions does all the same steps as Travis CI except [one part ](https://github.com/linz/linz-bde-perl/blob/39e16b209e35bcdf3e8326a337d968125fcd9de5/.travis.yml#L18-L19)that deletes /dev/stdout and then reruns the tests again. Looks like that is supposed to test [this part of the code](https://github.com/linz/linz-bde-perl/blob/39e16b209e35bcdf3e8326a337d968125fcd9de5/lib/LINZ/Bde.pm#L538-L569).

**Comment by l0b0** [comment]
> Looks like Github actions does all the same steps as Travis CI except [one part ](https://github.com/linz/linz-bde-perl/blob/39e16b209e35bcdf3e8326a337d968125fcd9de5/.travis.yml#L18-L19)that deletes /dev/stdout and then reruns the tests again. Looks like that is supposed to test [this part of the code](https://github.com/linz/linz-bde-perl/blob/39e16b209e35bcdf3e8326a337d968125fcd9de5/lib/LINZ/Bde.pm#L538-L569). Maybe that is in there to work around something on Travis itself though?

I can't see any mention of it being a problem except on Travis itself (and Windows, which is irrelevant). I'd be in favour of ripping this functionality out and checking whether the code still works in CI. If it does it's likely to also work without this workaround in production.

**Comment by billgeo** [comment]
> and checking whether the code still works in CI

Do you mean taking it out and running it on Travis CI? And if it's all fine then leave it out of the Github CI?

**Comment by l0b0** [comment]
> > and checking whether the code still works in CI
> 
> Do you mean taking it out and running it on Travis CI? And if it's all fine then leave it out of the Github CI?

No, I mean if it still passes GitHub CI we should be good.
